name: Deploy

# This is an exmample workflow to deploys the build outputs to their various
# destinations.

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/setup-node-env

      - run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist

  deploy:
    needs: build

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        include:
          - target: server
          - target: client

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist

      # Now do something with the build output

      - name: Deploy ${{ matrix.target }}
        run: '${{ matrix.target }}.js $(gzip -c ${{ matrix.target }}.js | wc -c) bytes (gzipped)'

      # etc...
