name: CI

on:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - check: types
          - check: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/setup-node-env

      - run: pnpm ${{ matrix.check }}
